/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const main: string;
declare const panel: string;
declare const contentPanel: string;
declare const form: string;
declare const button: string;

export {
	main,
	panel,
	contentPanel,
	form,
	button
};

declare const __default_export__: {
	main: typeof main;
	panel: typeof panel;
	contentPanel: typeof contentPanel;
	form: typeof form;
	button: typeof button;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQXV0aFBhZ2UubW9kdWxlLnNjc3MuZC50cyIsInNvdXJjZXMiOlsiQXV0aFBhZ2UubW9kdWxlLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7OztjQUVBO2NBTUE7Y0FNQTs7Ozs7Q0FaQTtDQU1BO0NBTUE7Ozs7OztDQVpBO0NBTUE7Q0FNQTs7In0=
