/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const main: string;
declare const panel: string;
declare const leftPanel: string;
declare const contentPanel: string;

export {
	main,
	panel,
	leftPanel,
	contentPanel
};

declare const __default_export__: {
	main: typeof main;
	panel: typeof panel;
	leftPanel: typeof leftPanel;
	contentPanel: typeof contentPanel;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiSG9tZVBhZ2UubW9kdWxlLnNjc3MuZC50cyIsInNvdXJjZXMiOlsiSG9tZVBhZ2UubW9kdWxlLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7OztjQUVBO2NBTUE7Ozs7O0NBTkE7Q0FNQTs7Ozs7O0NBTkE7Q0FNQTs7In0=
