/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const leftPanel: string;
declare const contentPanel: string;
declare const main: string;

export {
	panel,
	leftPanel,
	contentPanel,
	main
};

declare const __default_export__: {
	panel: typeof panel;
	leftPanel: typeof leftPanel;
	contentPanel: typeof contentPanel;
	main: typeof main;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQXBwLm1vZHVsZS5zY3NzLmQudHMiLCJzb3VyY2VzIjpbIkFwcC5tb2R1bGUuc2NzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Y0FjQTtjQU1BO2NBbEJBOzs7O0NBWUE7Q0FNQTtDQWxCQTs7Ozs7Q0FZQTtDQU1BO0NBbEJBOzsifQ==
